Update API
proximax-storage/go-xpx-dfms-api-http pull request #49
Opened 2020-11-17 15:42 UTC by jenyasd209

related to https://github.com/proximax-storage/go-xpx-dfms-api/pull/41

2020-11-17 15:44 UTC, xgreenx approved these changes

2020-11-18 10:31 UTC, Wondertan requested changes

2020-11-18 10:31 UTC, Wondertan commented on drive_fs.go
> +// If there are no more references then removes the file locally
```suggestion
// If the file is cached and no more references left it clears the cache.
```

2020-11-19 10:52 UTC, Wondertan approved these changes

2020-11-19 11:02 UTC, merged