Ledger interface
proximax-storage/go-xpx-dfms-api-http pull request #55
Opened 2021-01-26 13:50 UTC by Cempl

2021-01-26 15:52 UTC, jenyasd209 requested changes

2021-01-26 15:52 UTC, jenyasd209 commented on ledger.go
> +func (api *apiLedger) ListDrives(ctx context.Context) ([]drive.ID, error) {
You need to implement the new command in `go-xpx-dfms`, (e.g. `ledger/drives`) and use it.

And look at `apiContractClient.List()`, it has similar goal.

2021-01-28 09:22 UTC, jenyasd209 approved these changes

2021-01-28 15:03 UTC, Wondertan approved these changes

2021-02-19 07:33 UTC, merged